/**
 * Shared types for the tax calculator.
 *
 * Design rule for the whole project: every number produced here comes from a
 * config value or a user input. Nothing is ever generated by a model.
 */

export type TaxpayerCategory =
  | 'general'
  | 'female_or_senior_65_plus'
  | 'person_with_disability'
  | 'third_gender'
  | 'gazetted_freedom_fighter';

/** A slab band applied ABOVE the exempt threshold. `width: null` = remainder. */
export interface Band {
  width: number | null;
  rate: number;
}

export interface YearConfig {
  assessment_year: string;
  income_year: { from: string; to: string };
  filing_deadline?: string;
  verified: boolean;
  source: string;

  exempt_threshold: Record<TaxpayerCategory, number>;
  parent_of_disabled_extra: number;
  bands: Band[];

  rebate: {
    pct_of_taxable_income: number;
    pct_of_investment: number;
    absolute_cap: number;
    eligible_categories: string[];
  };

  minimum_tax: {
    standard: number;
    first_time_filer: number;
    applies_when: 'total_income_above_threshold' | 'always';
  };

  salary_exemption: {
    mode: 'itemized' | 'overall_cap' | 'fraction_of_gross';
    /** Used when mode is fraction_of_gross — use rationals, not 0.3333. */
    fraction?: { numerator: number; denominator: number };
    /** Max exemption when mode is fraction_of_gross (UNVERIFIED above ~13.5L salary). */
    absolute_cap?: number | null;
    house_rent_pct_of_basic: number | null;
    medical_annual_cap: number | null;
    conveyance_annual_cap: number | null;
    overall_cap: number | null;
  };

  house_property: {
    repair_allowance_pct: number | null;
  };
}

export interface TaxInputs {
  category: TaxpayerCategory;
  is_parent_of_disabled: boolean;
  is_first_time_filer: boolean;

  salary: {
    basic: number;
    house_rent_allowance: number;
    medical_allowance: number;
    conveyance_allowance: number;
    bonus: number;
    other_allowances: number;
    non_cash_benefits: number;
  };

  /** NET house property income (see config.house_property note). */
  house_property_income: number;
  bank_interest: number;
  other_income: number;

  /** Total investment across eligible categories. */
  eligible_investment: number;

  /** Already-paid amounts, deducted at the end. */
  source_tax: number;
  advance_tax: number;
}

export interface BandRow {
  band: string;
  width: number | null;
  rate: number;
  amount_taxed: number;
  tax: number;
}

export interface Breakdown {
  assessment_year: string;
  config_verified: boolean;

  gross_salary: number;
  salary_exemption: number;
  taxable_salary: number;

  house_property_income: number;
  bank_interest: number;
  other_income: number;
  total_income: number;

  exempt_threshold: number;
  taxable_above_threshold: number;

  band_rows: BandRow[];
  gross_tax: number;

  rebate: number;
  /** Which of the three rebate caps actually bound — useful for explanation. */
  rebate_binding: 'income' | 'investment' | 'cap' | 'none';

  tax_after_rebate: number;
  minimum_tax_applied: boolean;
  net_tax: number;

  source_tax: number;
  advance_tax: number;
  payable: number;
  refundable: number;

  /** Anything the user should be told the calculator could not handle. */
  warnings: string[];
}
